### PR TITLE
Upgrade mapbox

### PR DESCRIPTION
**Pull request by fc**
@ryanhamley
Now that mapbox-gl-js 0.51.0 is out...can someone review / merge this?

This closes out the journey that began with the localStorage issue, ref:  https://github.com/mapbox/mapbox-gl-js/pull/7455

Also, addresses #33

### CODE REVIEW

**Comment by fc** [comment]
Also -- in addition to this, would it be possible to both issue a new release too and publish that version to npm? This would also close out #25 since the current version on npm is out of date.

**Comment by fc** [comment]
If anyone wants to use this, you can do this:
```
yarn add fc/mapbox-gl-js-mock#upgrade-mapbox
```

**Comment by ryanhamley** [comment]
Hi @fc thanks for your patience. Would you mind sharing what your use case is for mapbox-gl-js-mock? We are not actively maintaining it and would caution developers who use it as a test suite for GL JS that it’s outdated, so what can be done with it is limited. That said, I think updating it to solve the fix from https://github.com/mapbox/mapbox-gl-js/pull/7455 makes sense so we’ll go ahead and create a new release for this and publish it to npm. Thanks!

**Comment by fc** [comment]
Thanks, @ryanhamley !

In a nutshell, we have a lightweight wrapper around `mapbox-gl-js`.

**Comment by ryanhamley** [comment]
Hey, I'm actually noticing now that I merged that our CircleCI is failing (there's no CI on dev branches in this repo) and the `npm test` command no longer works. Are you not experiencing issues in your test set up with this change? I'm starting to think that the code has diverged too significantly for this update to be very useful because GL JS is heavily reliant on ES6 modules.

**Comment by fc** [comment]
Ahhh.... you are correct, sorry.
I am using this to run my tests (a jest parameter):
```
--transformIgnorePatterns 'node_modules/(?!(mapbox-gl))'
```
I understand if you need to revert.

**Comment by ryanhamley** [comment]
I think reverting is best here, unfortunately. This repo isn’t really equipped to work with the fully ES6 code of newer versions of GL JS and is fairly out of date and limited. If it’s working for you, that’s great but I think our team is going to have to consider deprecating it because we don’t have the resources to update and maintain this repo at this time

**Pull request merged**
